### ISSUE TITLE
Characters out of ASCII range do not behave correctly

### ISSUE THREAD

**Issue by ntietz** [hannujaakkola/rot26#2]
My understanding of ROT-k is that anything outside of ASCII range should be left alone.

I would expect the following behavior: `decrypt(encrypt('123ABC')) === '123ABC'`

However, the following happens: `decrypt(encrypt('123ABC')) === 'KLMABC'`

**Comment by hannujaakkola** [comment]
Thank you for your contribution and making the world a more secure place for all of us.
